"""alembic upgrade head against an empty temp DB, table/index shape, and the
downgrade/upgrade roundtrip.

`alembic check` is exercised too, but is not asserted to be perfectly clean:
SQLAlchemy's sqlite reflection cannot compute a reliable signature for an
index with a `desc()`-ordered column (`idx_tx_user_recent`), a documented
upstream limitation (see alembic.ddl.impl.DefaultImpl.compare_indexes), and it
cannot see a column-level CHECK installed by `ALTER TABLE ADD COLUMN` either,
so the ORM's matching declaration always reads as "added". The DDL itself is
verified directly instead. Any *other* diff still fails the test, which is what
actually guards against ORM/migration drift.
"""

import asyncio
import re
import sqlite3
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command
from catetin.adapters.outbound.persistence.engine import create_writer_engine
from catetin.adapters.outbound.persistence.version_check import check_db_revision
from catetin.config import Settings

REPO_ROOT = Path(__file__).resolve().parents[2]

# Column-level CHECKs added by `ALTER TABLE ADD COLUMN` in 0002/0003. SQLite
# reflection does not surface them, so `alembic check` always reports the ORM's
# declarations as additions — see this module's docstring.
UNREFLECTED_INLINE_CHECKS = {
    "ck_transactions_flagged_bool",
    "ck_transactions_excluded_from_report_bool",
    "ck_users_onboarded_bool",
}

EXPECTED_TABLES = {
    "users",
    "transactions",
    "inbox",
    "parse_failures",
    "rate_limits",
    "alembic_version",
}


def _cfg(database_url: str, monkeypatch: pytest.MonkeyPatch) -> Config:
    monkeypatch.setenv("CATETIN_DATABASE_URL", database_url)
    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    return cfg


def _sqlite_path(database_url: str) -> str:
    return database_url.removeprefix("sqlite+aiosqlite:///")


def test_upgrade_head_creates_all_tables(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    command.upgrade(_cfg(database_url, monkeypatch), "head")

    conn = sqlite3.connect(_sqlite_path(database_url))
    try:
        tables = {
            row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
    finally:
        conn.close()

    assert EXPECTED_TABLES <= tables


def test_rate_limits_is_without_rowid(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    command.upgrade(_cfg(database_url, monkeypatch), "head")

    conn = sqlite3.connect(_sqlite_path(database_url))
    try:
        sql = conn.execute(
            "SELECT sql FROM sqlite_master WHERE name='rate_limits'"
        ).fetchone()[0]
    finally:
        conn.close()

    assert "WITHOUT ROWID" in sql


def test_partial_indexes_created(database_url: str, monkeypatch: pytest.MonkeyPatch) -> None:
    command.upgrade(_cfg(database_url, monkeypatch), "head")

    conn = sqlite3.connect(_sqlite_path(database_url))
    try:
        rows = dict(
            conn.execute(
                "SELECT name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL"
            ).fetchall()
        )
    finally:
        conn.close()

    for name in (
        "idx_tx_user_date",
        "idx_tx_user_recent",
        "idx_tx_user_item",
        "idx_users_digest",
        "idx_inbox_unprocessed",
    ):
        assert name in rows, f"missing index {name}"
        assert "WHERE" in rows[name], f"{name} is not a partial index: {rows[name]}"

    assert "DESC" in rows["idx_tx_user_recent"]


def test_has_onboarded_column_exists_and_defaults_to_false(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """0003: every user that predates the `/start` flow must come out of the
    migration as "not onboarded yet" without a data backfill."""
    command.upgrade(_cfg(database_url, monkeypatch), "head")

    conn = sqlite3.connect(_sqlite_path(database_url))
    try:
        columns = {row[1]: row for row in conn.execute("PRAGMA table_info(users)")}
        assert "has_onboarded" in columns
        _, _, col_type, notnull, default, _ = columns["has_onboarded"]
        assert col_type == "INTEGER"
        assert notnull == 1
        assert default == "0"

        conn.execute(
            "INSERT INTO users (platform, platform_user_id) VALUES ('telegram', '1')"
        )
        assert conn.execute("SELECT has_onboarded FROM users").fetchone()[0] == 0
    finally:
        conn.close()


def test_downgrade_base_then_upgrade_head_roundtrips(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    cfg = _cfg(database_url, monkeypatch)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    conn = sqlite3.connect(_sqlite_path(database_url))
    try:
        tables = {
            row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
    finally:
        conn.close()
    assert tables.isdisjoint(EXPECTED_TABLES - {"alembic_version"})

    command.upgrade(cfg, "head")  # must still be re-appliable


def test_check_db_revision_passes_against_migrated_db(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    # command.upgrade() drives alembic/env.py, which does its own asyncio.run() —
    # this test (and the async check below) must therefore stay outside
    # pytest-asyncio's event loop, or asyncio.run() would nest and raise.
    command.upgrade(_cfg(database_url, monkeypatch), "head")

    settings = Settings(
        telegram_bot_token="test-token",
        telegram_webhook_secret="test-secret",
        ops_username="test-ops",
        ops_password="test-ops-pass",
        database_url=database_url,
    )

    async def _check() -> None:
        engine = create_writer_engine(settings)
        try:
            await check_db_revision(engine, settings.expected_db_revision)
        finally:
            await engine.dispose()

    asyncio.run(_check())


def test_check_db_revision_fails_against_empty_db(database_url: str) -> None:
    settings = Settings(
        telegram_bot_token="test-token",
        telegram_webhook_secret="test-secret",
        ops_username="test-ops",
        ops_password="test-ops-pass",
        database_url=database_url,
    )

    async def _check() -> None:
        engine = create_writer_engine(settings)
        try:
            with pytest.raises(RuntimeError, match="alembic_version table missing"):
                await check_db_revision(engine, settings.expected_db_revision)
        finally:
            await engine.dispose()

    asyncio.run(_check())


def test_alembic_check_has_no_unexpected_drift(
    database_url: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    cfg = _cfg(database_url, monkeypatch)
    command.upgrade(cfg, "head")

    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        message = str(exc)
        assert "idx_tx_user_recent" in message, message
        # Nothing may be reported except index churn and check constraints —
        # an added/removed/altered column or table is real drift.
        for operation in ("add_column", "remove_column", "add_table", "remove_table", "modify_"):
            assert operation not in message, message
        # ...and the only check constraints alembic may claim are "added" are
        # the inline ones ALTER TABLE ADD COLUMN installed (0002, 0003), which
        # SQLite does not reflect, so the ORM's copy always looks new.
        constraints = set(re.findall(r"name='(ck_\w+)'", message))
        assert constraints <= UNREFLECTED_INLINE_CHECKS, message
