"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-15

Hand-written, not autogenerated: partial indexes and WITHOUT ROWID are
SQLite-specific constructs that autogenerate does not reliably round-trip.
op.execute() carries those; op.create_table() carries the rest.
"""

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("platform_user_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text()),
        sa.Column("business_name", sa.Text()),
        sa.Column(
            "timezone", sa.Text(), nullable=False, server_default=sa.text("'Asia/Jakarta'")
        ),
        sa.Column("digest_enabled", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("blocked_at", sa.Integer()),
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default=sa.text("(unixepoch())")
        ),
        sa.Column(
            "updated_at", sa.Integer(), nullable=False, server_default=sa.text("(unixepoch())")
        ),
        sa.CheckConstraint("platform IN ('telegram','whatsapp')", name="platform_known"),
        sa.CheckConstraint("digest_enabled IN (0,1)", name="digest_bool"),
        sqlite_autoincrement=True,
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_users_platform_uid ON users (platform, platform_user_id)"
    )
    op.execute("CREATE INDEX idx_users_digest ON users (digest_enabled) WHERE blocked_at IS NULL")

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("item", sa.Text(), nullable=False, server_default=sa.text("'(tanpa nama)'")),
        sa.Column("qty", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("unit_amount", sa.Integer()),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("occurred_on", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False, server_default=sa.text("'regex'")),
        sa.Column("confidence", sa.REAL(), nullable=False, server_default=sa.text("1.0")),
        sa.Column("raw_text", sa.Text()),
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default=sa.text("(unixepoch())")
        ),
        sa.Column("deleted_at", sa.Integer()),
        sa.CheckConstraint("kind IN ('sale','expense')", name="kind_known"),
        sa.CheckConstraint("qty > 0", name="qty_positive"),
        sa.CheckConstraint(
            "unit_amount IS NULL OR unit_amount >= 0", name="unit_amount_nonneg"
        ),
        sa.CheckConstraint("total_amount > 0", name="total_amount_positive"),
        sa.CheckConstraint(
            "source IN ('regex','llm','manual')", name="source_known"
        ),
        sqlite_autoincrement=True,
    )
    op.execute(
        "CREATE INDEX idx_tx_user_date ON transactions (user_id, occurred_on) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX idx_tx_user_recent ON transactions (user_id, created_at DESC) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX idx_tx_user_item ON transactions (user_id, kind, item) "
        "WHERE deleted_at IS NULL"
    )

    op.create_table(
        "inbox",
        sa.Column("update_id", sa.Integer(), primary_key=True),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column(
            "received_at", sa.Integer(), nullable=False, server_default=sa.text("(unixepoch())")
        ),
        sa.Column("processed_at", sa.Integer()),
    )
    op.execute(
        "CREATE INDEX idx_inbox_unprocessed ON inbox (received_at) WHERE processed_at IS NULL"
    )

    op.create_table(
        "parse_failures",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
        ),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.Integer(), nullable=False, server_default=sa.text("(unixepoch())")
        ),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_parse_failures_time", "parse_failures", ["created_at"])

    # WITHOUT ROWID: raw DDL per the design docs — halves the footprint of a
    # small composite-key table. Kept in sync manually with orm.RateLimitRow.
    op.execute(
        """
        CREATE TABLE rate_limits (
            user_id INTEGER NOT NULL,
            bucket TEXT NOT NULL,
            window_start INTEGER NOT NULL,
            count INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (user_id, bucket, window_start),
            CONSTRAINT fk_rate_limits_user_id_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        ) WITHOUT ROWID
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE rate_limits")
    op.drop_index("idx_parse_failures_time", table_name="parse_failures")
    op.drop_table("parse_failures")
    op.execute("DROP INDEX idx_inbox_unprocessed")
    op.drop_table("inbox")
    op.execute("DROP INDEX idx_tx_user_item")
    op.execute("DROP INDEX idx_tx_user_recent")
    op.execute("DROP INDEX idx_tx_user_date")
    op.drop_table("transactions")
    op.execute("DROP INDEX idx_users_digest")
    op.execute("DROP INDEX idx_users_platform_uid")
    op.drop_table("users")
