"""report v1 — flag + exclude columns on transactions

Revision ID: 0002_report_scope
Revises: 0001_initial
Create Date: 2026-08-18

Hand-written, not autogenerated — same reasoning as 0001_initial: SQLite
ADD COLUMN with inline CHECK is a raw-DDL concern autogenerate does not
reliably round-trip. Both new columns default 0, so existing rows become
"business, not flagged" automatically (NFR-4).
"""

from alembic import op

revision = "0002_report_scope"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE transactions ADD COLUMN flagged INTEGER NOT NULL "
        "DEFAULT 0 CHECK(flagged IN (0,1))"
    )
    op.execute(
        "ALTER TABLE transactions ADD COLUMN excluded_from_report INTEGER NOT NULL "
        "DEFAULT 0 CHECK(excluded_from_report IN (0,1))"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE transactions DROP COLUMN excluded_from_report")
    op.execute("ALTER TABLE transactions DROP COLUMN flagged")
